### ISSUE TITLE
Repository not consistent with LinkedIn course and doesn't work on Windows

### ISSUE THREAD

**Issue by afattacc** [LinkedInLearning/learning-elixir-2898718#4]
## Issue Overview
Repository not consistent with LinkedIn course and doesn't work on Windows. Issue appears in chapter 8 and onward.

## Describe your environment
Windows terminal

## Steps to Reproduce
1. git checkout 08_01b
2. git checkout 08_02b
3.
4.

## Expected Behaviour
- chap_08 folder and exercise file are found in 08_ 01b
- chap_08/convention folder and exercise files and found in 08_02b

## Current Behaviour

- chap_08 and exercise file entirely missing in 08_01b
- "convention" folder renamed to "con" in 08_02b which is not a valid folder name in Windows.  So, the checkout fails for 08_02b and subsequent branches.

**Comment by vanessaklee** [comment]
Thank you for the detailed issue report. Issues have been fixed.

- chap_08 directory and exercise file are now in branch 08_01b ([commit](https://github.com/LinkedInLearning/learning-elixir-2898718/commit/0624a6d86d9aae0ea564c56c95d27734188cc39b)) 
- chap_08/convention directory and exercise files are now in branch 08_02b ([commit](https://github.com/LinkedInLearning/learning-elixir-2898718/commit/b70608062dc7bfa1342e4a6bf84fd7b703d6d0f9#diff-f855e5926012669fc6b70869e8ed58436136a8a1f6f769a6ea3bbd452d75bafa))
